### ISSUE TITLE
AtOnboardingCli throws exception when atsign does not contain an '@' symbol

### ISSUE THREAD

**Issue by srieteja** [atsign-foundation/at_libraries#299]
### Describe the bug

When an instance of AtOnboardingCli with an atsign that does not contain '@' symbol an exception is thrown. Ideally, that atsign should be fixed by inserting an '@' at the beginning of the atsign. This fix is being triggered in AtOnboardingCli but is being done incorrectly.

### Steps to reproduce

1. First I create a valid instance of AtOnboardingPreferences, the instance name is say _prefs_
2. Then I create an instance of AtOnboardingCli -> var service = AtOnboardingServiceImpl('atsign_without_@_prefix', prefs);
3. This results in the following exception:
````
Unhandled exception:
Exception: invalid @sign: must include one @ character and at least one character on the right
#0      AtUtils.fixAtSign (package:at_utils/src/atsign_util.dart:31:7)
#1      new AtOnboardingServiceImpl (package:at_onboarding_cli/src/onboard/at_onboarding_service_impl.dart:30:44)
#2      main (package:at_onboarding_cli/src/activate_cli/activate_cli.dart:54:7)
````

### Expected behaviour

A valid instance of AtOnboardingService should be created, implying that the atsign passed should be prefixed with '@' when there isn't one.

**Comment by srieteja** [comment]
A better solution to this issue is mentioned at https://github.com/atsign-foundation/at_tools/issues/293.
This ticket will be on hold until the solution mentioned in the other ticket has been implemented and consumed here.
